package lesson0107a;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class CalcWindow extends JFrame {
    JTextField text;
    JLabel label;

    public CalcWindow() throws HeadlessException {
        setTitle("The Simplest Calculator");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBounds(400, 200, 500, 75);
        setLayout(new BoxLayout(getContentPane(), BoxLayout.X_AXIS));

        text = new JTextField();
        text.setColumns(35);
        text.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String s = Character.toString(ch);
                if (Character.isDigit(ch) || ch == '+' || ch == '-' || ch == '*' || ch == '/') {
                    label.setText(s);
                    label.updateUI();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });

        label = new JLabel(" = ...................");

        add(text);
        add(label);

        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
