package lesson0107a;

import javax.swing.*;
import java.awt.*;

public class CalculateWindow extends JFrame {
    private JTextField textField;
    private JSlider slider;
    // TODO: place custom component creation code here
    private JPanel panel = new JPanel();
    private JLabel label;

    private void createUIComponents() {
        setContentPane(panel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        pack();
        setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.setName("");
        panel.setPreferredSize(new Dimension(400, 150));
        textField = new JTextField();
        textField.setHorizontalAlignment(0);
        panel.add(textField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 1, false));
        label = new JLabel();
        label.setHorizontalAlignment(0);
        label.setText("Label");
        panel.add(label, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        slider = new JSlider();
        slider.setMajorTickSpacing(4);
        slider.setMaximum(4);
        slider.setMinimum(0);
        slider.setMinorTickSpacing(1);
        slider.setName("Digits after comma");
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setSnapToTicks(false);
        slider.setValue(2);
        slider.setValueIsAdjusting(false);
        slider.putClientProperty("JSlider.isFilled", Boolean.FALSE);
        slider.putClientProperty("Slider.paintThumbArrowShape", Boolean.FALSE);
        slider.putClientProperty("html.disable", Boolean.FALSE);
        panel.add(slider, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
